# Generated by Django 4.2.6 on 2024-02-09 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('age', models.IntegerField(null=True, verbose_name='Возраст')),
                ('total_rating', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='Рейтинг')),
                ('user_count', models.IntegerField(blank=True, null=True, verbose_name='Кол-во оценок')),
                ('photo', models.URLField(blank=True, null=True, verbose_name='Фото')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время публикации')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Дама',
                'verbose_name_plural': 'Дамы',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Категория')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ArticleRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('face', models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='Лицо')),
                ('figure', models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='Фигура')),
                ('tits', models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='Тема сисек')),
                ('ass', models.DecimalField(decimal_places=1, default=0.0, max_digits=5, verbose_name='Жопа')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='scores.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Оценка',
                'verbose_name_plural': 'Оценки',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='scores.category'),
        ),
        migrations.AddField(
            model_name='article',
            name='ratings',
            field=models.ManyToManyField(through='scores.ArticleRating', to=settings.AUTH_USER_MODEL),
        ),
    ]
