# Generated by Django 3.1 on 2023-10-16 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0003_auto_20231016_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='total_rating',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='article',
            name='user_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кол-во оценок'),
        ),
    ]
