# Generated by Django 3.1 on 2023-10-23 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scores', '0005_auto_20231016_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Дама', 'verbose_name_plural': 'Дамы'},
        ),
        migrations.AlterField(
            model_name='article',
            name='cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scores.category'),
        ),
        migrations.AlterField(
            model_name='articlerating',
            name='ass',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Жопа'),
        ),
        migrations.DeleteModel(
            name='Tyans',
        ),
    ]
